version: '3.8'
services:
  mongodb:
    image: mongo:6
    container_name: hangul-db
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb_data:/data/db
    networks:
      - hangul-network

  api:
    build: .
    container_name: hangul-api
    restart: always
    depends_on:
      - mongodb
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - hangul-network

volumes:
  mongodb_data:

networks:
  hangul-network:
    driver: bridge
